# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a707ffcad54fde6cb1463dfb03b7d0de"
application_url = "https://communist-quotations-nhs-acm.trycloudflare.com"
embedded = true
name = "stripe-console"
handle = "stripe-console-management"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"
	
	# [[webhooks.subscriptions]]
  	# uri = "/webhooks/app/uninstalled"
  	# topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://communist-quotations-nhs-acm.trycloudflare.com/auth/callback", "https://communist-quotations-nhs-acm.trycloudflare.com/auth/shopify/callback", "https://communist-quotations-nhs-acm.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
